storePassword.debug=wmimo
keyPassword.debug=wmimo
keyAlias.debug=wmimo
storeFile.debug=app/wmimo.release.keystore
   
storePassword.release=wmimo
keyPassword.release=wmimo
keyAlias.release=wmimo
storeFile.release=app/wmimo.release.keystore
