storePassword.debug=wmimo
keyPassword.debug=wmimo
keyAlias.debug=wmimo
storeFile.debug=../../private_for_build/wmimo/wmimo/android/sign/wmimo.release.keystore
   
storePassword.release=wmimo
keyPassword.release=wmimo
keyAlias.release=wmimo
storeFile.release=../../private_for_build/wmimo/wmimo/android/sign/wmimo.release.keystore
