[package]
name = "wmimo_client"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
wmimo_common = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
futures-util = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
url = { workspace = true }
